- name: Create Resource Group
  hosts: all
  collections:
    - azure.azcollection
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "appvm"
        location: "EAST US"
