- hosts: all
  gather_facts: yes
  vars:
    ansible_python_interpreter: /bin/python3.12
  collections:
    - azure.azcollection
  roles:
    - role: resource_group
    
    - role: network_interface
    
    - role: create_vm
    
    - role: create_disk
      when: create_additional_disks == "Yes"

    
       
