- hosts: all
  gather_facts: yes
  vars:
    ansible_python_interpreter: /bin/python3.12
  collections:
    - azure.azcollection
  roles:
    - resource_group
    - network_interface
    - create_vm
    
       
