---
- name: Convert comma-separated disk sizes to list
  set_fact:
    disk_sizes_list: "{{ additional_disk_sizes.split(',') | map('trim') | map('int') }}"

- name: Debug disk sizes list
  debug:
    var: disk_sizes_list

- name: Create and attach data disks
  azure_rm_manageddisk:
    resource_group: "{{ rg_name }}"
    name: "{{ hostname }}_data_disk_{{ item }}"
    disk_size_gb: "{{ item }}"
    create_option: "empty"
    storage_account_type: "Standard_LRS"
  with_items: "{{ disk_sizes_list }}"
  register: data_disks

- name: Attach data disks to the virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: "{{ hostname }}"
    data_disks: 
      "{{ data_disks.results | map(attribute='state.id') | list | map('community.general.dict_kv', 'lun') }}"
  when: data_disks is defined
