---
- name: Convert comma-separated disk sizes to list
  set_fact:
    disk_sizes_list: "{{ additional_disk_sizes.split(',') | map('trim') | map('int') }}"

- name: Debug disk sizes list
  debug:
    var: disk_sizes_list

- name: Set disk as gather_facts
  set_stats:
    data:
      disk_sizes_list: "{{disk_sizes_list}}"



- name: Create data disks
  azure_rm_manageddisk:
    resource_group: "{{ rg_name }}"
    name: "{{ hostname }}_data_disk_{{ item }}"
    disk_size_gb: "{{ item }}"
    create_option: "empty"
    attach_caching: read_write
    storage_account_type: "Standard_LRS"
    managed_by: "{{hostname}}" 
  with_items: "{{ disk_sizes_list }}"
  register: data_disks

- name: Build data disks with LUN mapping
  set_fact:
    lun_disks: "{{ lun_disks | default([]) + [{'managed_disk_id': item.state.id, 'lun': index}] }}"
  loop: "{{ data_disks.results }}"
  loop_control:
    index_var: index

- name: Debug LUN-disks mapping
  debug:
    var: lun_disks

- name: Attach data disks to the virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: "{{ hostname }}"
    data_disks: "{{ lun_disks }}"
  when: lun_disks is defined



  
