- name: Create Azure VM
  azure_rm_virtualmachine:
    name: "{{hostname}}"
    resource_group: "{{rg_name}}"
    network_interface_names: 
      - "{{hostname}}_nic"
    vm_size: "{{vm_size}}"
    admin_username: "{{admin_user}}"
    admin_password: "{{admin_password}}"
    image:
      offer: windowsserver
      publisher: microsoftwindowsserver
      sku: 2022-datacenter-azure-edition-hotpatch
      version: latest
    location: "{{region}}"
    os_disk_caching: "ReadWrite"
    os_disk_size_gb: 100
    managed_disk_type: "Standard_LRS"
    os_type: Windows
    plan:
      name: 2022-datacenter-azure-edition-hotpatch        # This should match the offer or product name
      product: windowsserver
      publisher: microsoftwindowsserver
    accept_terms: true

- name: Ensure VM is running
  azure_rm_virtualmachine:
    resource_group: "{{rg_name}}"
    state: "present"

