- name: Create Azure VM
  azure_rm_virtualmachine:
    name: "{{hostname}}"
    resource_group: "{{rg_name}}"
    network_interface_names: 
      - "{{hostname}}_nic"
    vm_size: "{{vm_size}}"
    admin_username: "{{admin_user}}"
    admin_password: "{{admin_password}}"
    image:
      offer: 0001-com-ubuntu_server-jammy
      publisher: Canonical
      sku: 22_04_lts
      version: latest
    os_disk_caching: "ReadWrite"
    os_disk_size_gb: 30
    managed_disk_type: "Standard_LRS"

- name: Ensure VM is running
  azure_rm_virtualmachine:
    resource_group: "{{rg_name}}"
    state: "present"

