- name: Server Creation on process.
  block:
    - name: Include variables from vars/main.yml
      include_vars: "vars/main.yml"

    - name: Select the appropriate image based on OS type
      set_fact:
        selected_image:
          offer: "{{ images[Os_Type].offer }}"
          publisher: "{{ images[Os_Type].publisher }}"
          sku: "{{ images[Os_Type].sku }}"
          version: "{{ images[Os_Type].version }}"
      when: Os_Type in images
      

    - name: Create Azure VM
      azure_rm_virtualmachine:
        name: "{{ hostname }}"
        resource_group: "{{ rg_name }}"
        network_interface_names: 
          - "{{ hostname }}_nic"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        location: "{{ region }}"
        image:
          offer: "{{ selected_image.offer }}"
          publisher: "{{ selected_image.publisher }}"
          sku: "{{ selected_image.sku }}"
          version: "{{ selected_image.version }}"
        os_disk:
          managed_disk:
            id: "{{os_disk_id}}"
          caching: "ReadWrite"
 #       data_disks: "{% if additional_disk_size is defined and additional_disk_size | int > 0 %}[{'lun': 0, 'managed_disk': {'id': additional_disk_id}, 'disk_size_gb': additional_disk_size, 'managed_disk_type': additional_disk_type}]{% else %}[]{% endif %}"
        tags:
          owner: "{{ owner_email }}"
      register: vm

    - debug:
        var: vm
    
    - name: Ensure VM is running
      azure_rm_virtualmachine:
        resource_group: "{{ rg_name }}"
        name: "{{ hostname }}"
        state: "present"
