---
- include_vars: vars/main.yml
- set_fact:
    vnet: "Vnet-PROD"
    security_grp: "Baseline-CI"
  when: env == "PROD"

- set_fact:
    vnet: "Vnet-DEV"
    security_grp: "Baseline"
  when: env == "DEV"

- set_fact:
    vnet: "Vnet-TST"
    security_grp: "Baseline-NE"
  when: env == "TST" 

- name: Create Public IP for the network interface
  azure_rm_publicipaddress:
    name: "{{ hostname }}_public_ip"
    resource_group: "{{ rg_name }}"
    allocation_method: "Static"  
    location: "{{ region }}"  
    state: present
  register: public_ip

- debug:
    var: public_ip

- name: Create Vnet interface card for virtual machine
  azure_rm_networkinterface:
    name: "{{hostname}}_nic"
    resource_group: "{{rg_name}}"
    virtual_network:
      name: "{{vnet}}"
      resource_group: "{{vnet_rg}}"
#    location: "{{region}}"
    subnet_name: "{{layer}}"
    create_with_security_group: false
    security_group:
      name: "{{security_grp}}"
    ip_configurations:
      - name: ipconfig1
        primary: True
        private_ip_allocation_method: Dynamic
        public_ip_address: "public_ip.state.name"
    tags:
      Owner: "{{owner_email}}"
    api_profile: "latest"
  
  register: interface

- debug:
    var: interface

