---
- name: Include environment-specific variables
  include_vars: vars/main.yml

# Set virtual network and security group based on environment
- name: Set VNet and Security Group for PROD
  set_fact:
    vnet: "Vnet-PROD"
    security_grp: "Baseline-CI"
  when: env == "PROD"

- name: Set VNet and Security Group for DEV
  set_fact:
    vnet: "Vnet-DEV"
    security_grp: "Baseline"
  when: env == "DEV"

- name: Set VNet and Security Group for TST
  set_fact:
    vnet: "Vnet-TST"
    security_grp: "Baseline-NE"
  when: env == "TST"

# Create Public IP Address
- name: Create Public IP for the network interface
  azure_rm_publicipaddress:
    name: "{{ hostname }}_public_ip"
    resource_group: "{{ rg_name }}"
    allocation_method: "Static"
    location: "{{ region }}"
    state: present
  register: public_ip

- debug:
    var: public_ip

# Debug: Print the Public IP details
- name: Print Public IP Address details
  debug:
    msg: 
      - "Public IP Name: {{ public_ip.state.name }}"
      - "Public IP Address: {{ public_ip.state.ip_address }}"

- name: Set public IP as a fact
  set_fact:
    public_ip_address: "{{ public_ip.state.ip_address }}"

# Create Network Interface (NIC)
- name: Create Vnet interface card for virtual machine
  azure_rm_networkinterface:
    name: "{{hostname}}_nic"
    resource_group: "{{rg_name}}"
    virtual_network:
      name: "{{vnet}}"
      resource_group: "{{vnet_rg}}"  
    subnet_name: "{{layer}}"  
    create_with_security_group: false
    security_group:
      name: "{{security_grp}}"
    ip_configurations:
      - name: ipconfig1
        primary: True
        private_ip_allocation_method: Dynamic
        public_ip_address: "{{ hostname }}_public_ip"
    tags:
      Owner: "{{ owner_email }}"
    api_profile: "latest"
  
  register: interface

# Debug: Print the Network Interface details
- name: Print Network Interface details
  debug:
    msg: 
      - "Network Interface Name: {{ interface.state.name }}"
