- name: Create Azure resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ region }}"
    tags:
      Name: "{{ rg_name }}"
      Owner: "{{ owner_email }}"
      Environment: "{{ env }}"
    state: present
  register: rg_result

- debug:
    var: rg_result

- name: Debug resource group creation result
  debug:
    msg: "Resource group '{{ rg_name }}' created successfully in location '{{ region }}'."